export const products = [
    { id: 1, url: "https://picsum.photos/200/300", description: "Description 1", category: "Ceramics" },
    { id: 2, url: "https://picsum.photos/200/300", description: "Description 2", category: "Ceramics" },
    { id: 3, url: "https://picsum.photos/200/300", description: "Description 3", category: "Ceramics" },
    { id: 4, url: "https://picsum.photos/200/300", description: "Description 4", category: "Ceramics" },
    { id: 5, url: "https://picsum.photos/200/300", description: "Description 5", category: "Ceramics" },
    { id: 6, url: "https://picsum.photos/200/300", description: "Description 6", category: "Ceramics" },
    { id: 7, url: "https://picsum.photos/200/300", description: "Description 7", category: "Ceramics" },
    { id: 8, url: "https://picsum.photos/200/300", description: "Description 8", category: "Ceramics" },
    { id: 9, url: "https://picsum.photos/200/300", description: "Description 9", category: "Ceramics" },
    { id: 10, url: "https://picsum.photos/200/300", description: "Description 10", category: "Ceramics" },
   
    { id: 11, url: "https://picsum.photos/200/300", description: "Description 11", category: "Leather" },
    { id: 12, url: "https://picsum.photos/200/300", description: "Description 12", category: "Leather" },
    { id: 13, url: "https://picsum.photos/200/300", description: "Description 13", category: "Leather" },
    { id: 14, url: "https://picsum.photos/200/300", description: "Description 14", category: "Leather" },
    { id: 15, url: "https://picsum.photos/200/300", description: "Description 15", category: "Leather" },
    { id: 16, url: "https://picsum.photos/200/300", description: "Description 16", category: "Leather" },
    { id: 17, url: "https://picsum.photos/200/300", description: "Description 17", category: "Leather" },
    { id: 18, url: "https://picsum.photos/200/300", description: "Description 18", category: "Leather" },
    { id: 19, url: "https://picsum.photos/200/300", description: "Description 19", category: "Leather" },
    { id: 20, url: "https://picsum.photos/200/300", description: "Description 20", category: "Leather" },

    { id: 21, url: "https://picsum.photos/200/300", description: "Description 21", category: "Toys" },
    { id: 22, url: "https://picsum.photos/200/300", description: "Description 22", category: "Toys" },
    { id: 23, url: "https://picsum.photos/200/300", description: "Description 23", category: "Toys" },
    { id: 24, url: "https://picsum.photos/200/300", description: "Description 24", category: "Toys" },
    { id: 25, url: "https://picsum.photos/200/300", description: "Description 25", category: "Toys" },
    { id: 26, url: "https://picsum.photos/200/300", description: "Description 26", category: "Toys" },
    { id: 27, url: "https://picsum.photos/200/300", description: "Description 27", category: "Toys" },
    { id: 28, url: "https://picsum.photos/200/300", description: "Description 28", category: "Toys" },
    { id: 29, url: "https://picsum.photos/200/300", description: "Description 29", category: "Toys" },
    { id: 30, url: "https://picsum.photos/200/300", description: "Description 30", category: "Toys" },

    { id: 31, url: "https://picsum.photos/200/300", description: "Description 31", category: "Décor" },
    { id: 32, url: "https://picsum.photos/200/300", description: "Description 32", category: "Décor" },
    { id: 33, url: "https://picsum.photos/200/300", description: "Description 33", category: "Décor" },
    { id: 34, url: "https://picsum.photos/200/300", description: "Description 34", category: "Décor" },
    { id: 35, url: "https://picsum.photos/200/300", description: "Description 35", category: "Décor" },
    { id: 36, url: "https://picsum.photos/200/300", description: "Description 36", category: "Décor" },
    { id: 37, url: "https://picsum.photos/200/300", description: "Description 37", category: "Décor" },
    { id: 38, url: "https://picsum.photos/200/300", description: "Description 38", category: "Décor" },
    { id: 39, url: "https://picsum.photos/200/300", description: "Description 39", category: "Décor" },
    { id: 40, url: "https://picsum.photos/200/300", description: "Description 40", category: "Décor" },
  ];
  